### PR TITLE
[ci skip] Documents setting up a new machine with MESA TestHub

### LINKED ISSUE #277: Document process of setting up new machine with MESA TestHub
A good starting point may be Earl's pinned message in Slack.

### PR DESCRIPTION
**Pull request by earlbellinger**
Closes #277

### CODE REVIEW

**Comment by earlbellinger** [comment]
A screencap: 
image

**Comment by wmwolf** [comment]
Could you also add a blurb in step 1 about getting a token for submitting logs to the logs server? It will be provided by me at the time the account is set up and is needed during the `mesa_test setup` phase.

**Review by jschwab — APPROVED** [review]

**Comment by earlbellinger** [comment]
@wmwolf Is that what you had in mind?

**Comment by wmwolf** [comment]
Yep! Looks good to me.

**Review by wmwolf — APPROVED** [review]

**Comment by jschwab** [comment]
When you merge, this is a good candidate for a 'squash and merge'.  When the important thing is the net result and theintermediate, incremental history won't be interesting down the line, then 'squash and merge' is probably the way to go.

**Pull request merged**
