### PR TITLE
fixed reverse c12_to_he4_he4_he4 rate

### PR DESCRIPTION
**Pull request by Debraheem**
changed 'do1' to 'do1_reverse' for c12_to_he4_he4_he4 rate, as suggested by Evan Bauer. Fixes Helium burning issue, see https://github.com/MESAHub/mesa/issues/526#issue-1688392000

### CODE REVIEW

**Review by rjfarmer — CHANGES_REQUESTED** [review]
Dont add this file

When the build fails you can do:
cp rates/test/tmp.txt rates/test/test_output

and then when net fails do:
cp net/test/tmp.txt net/test/test_output

**Comment by rjfarmer** [comment]
You can add this to the changelog and known bugs:

````
Rates
~~~~~

There has been a bug present in the rate `r_c12_to_he4_he4_he4` since r21.12.1 up to r22.11.1. 
This causes an excessive amount of C12 to be burnt during core helium burning. 
Users are highly recommend to update to the latest MESA.

See `gh-526 <https://github.com/MESAHub/mesa/issues/526>`_`
````

**Review by rjfarmer — APPROVED** [review]

**Comment by evbauer** [comment]
I'll note that it looks like we had a refactor of a lot of this code in 15e034ba70aab432ff98b314541ce3fd8d274eac, which came between r21.12.1 and r22.05.1. So the bug didn't exist in this particular form in r21.12.1. For the changelog and known bugs documentation, I think we just want to say that this applies to r22.05.1 and r22.11.1.

**Comment by Debraheem** [comment]
Thanks Evan,

>"I think we just want to say that this applies to r22.05.1 and r22.11.1",

We confirmed that the issue did impact 21.12.1 right? Wouldn't we want to
warn users from using 21.12.1 as well, even if the bug existed in a
different form?

**Comment by rjfarmer** [comment]
Eb can you double check it affected 21.12.1? 15e034b was where the bug was added and that was committed on 2022-02-09. Maybe you had a stale local cache of the rates?

**Pull request merged**
