### PR TITLE
Flush files rather than close() them

### PR DESCRIPTION
**Pull request by rjfarmer**
This works on #169

@adamjermyn  can you have you cluster people see if this helps?

### CODE REVIEW

**Comment by rjfarmer** [comment]
Better hold off as I seem to have broken most test cases https://testhub.mesastar.org/rf%2Fflush-io/commits/68a1d0f

**Comment by warrickball** [comment]
I figured some of the failures might be `cannon`'s filesystem playing up so I also submitted it to `bluebear_ifort`. Most of the failures seem to be consistent across both systems. Many seem to happen because some output (looks like `history` data?) ends up being written to `stderr` and I think TestHub regards *anything* on `stderr` as a failure.

**Comment by rjfarmer** [comment]
I was actually worried this casued cannons failures...

There are at least 2 issues one is some history data gets outptted to terminal and two there is an issue with the pgstar.dat file

**Comment by rjfarmer** [comment]
Let see whats broken now https://testhub.mesastar.org/rf%2Fflush-io/commits/171cd41

**Comment by rjfarmer** [comment]
I'm closing this for now as it needs a bigger restructure than i was expecting

**Comment by matthiasfabry** [comment]
Do we have any idea why history data ended up on stderr with these changes? They seem sensible, or are there Fortran subtleties we'd be running into here?

**Comment by fxt44** [comment]
maybe one thread is still writing/flushing while another thread is closing?

**Comment by matthiasfabry** [comment]
That seems weird. Do multiple threads need to write to the same file? Also Rob's changes do not mention `close` anymore. In any case, could this be tested with `!$OMP CRITICAL`'s?

**Pull request closed without merging**
