### PR TITLE
Avoid some numerically messy subtractions in the EOS

### PR DESCRIPTION
**Pull request by evbauer**
This overwrites the radiation pressure that `auto_diff` would calculate to be $(\rho^2/\rho^2)aT^4/3$. Getting rid of the $(\rho^2/\rho^2)$ term avoids numerical problems for derivatives of radiation pressure with respect to $\rho$.

Should solve #589.

### CODE REVIEW

**Comment by fxt44** [comment]
are you sure an only explicit  prad is needed, not erad and srad?

**Comment by evbauer** [comment]
> are you sure an only explicit prad is needed, not erad and srad?

Nope! I'm not sure at all. I'll take a look at that soon. I've converted this PR to a draft in the mean time. Thanks for the guidance!

**Comment by fxt44** [comment]
i suspect you'll find 'em if you scour other derivative based quantities! broadly, in the "chemical picture" its best (as in it avoids swamping issues) to do radiation, ions, and e+e- separately and add.

**Comment by evbauer** [comment]
@rhdtownsend I was a bit surprised to see that `gyre_in_mesa_rsg` is fragile enough to be sensitive to tiny changes in the numerics of the EOS. I ended up changing the target frequency by almost 4%. Does that fix sound okay to you?

**Pull request merged**
