### PR TITLE
Binary time delta coeff

### PR DESCRIPTION
**Pull request by matthiasfabry**
Addresses #288. 
Apart from having a maybe a unit test this should be ready to be tested on the suite

### CODE REVIEW

**Comment by matthiasfabry** [comment]
Why did my push trigger the `Build MESA` action? I don't think I did anything abnormal

**Comment by warrickball** [comment]
This has just failed to compile on `bluebear_ifort` because the unit test has unformatted write statements. Different compilers have different default output styles, so the diffs fail if the format is unspecified. The solution, which I'll try to fix over the weekend since I have the ifort build, is just to use explicit formats. Some common formats are defined in `include/formats` (which is what some other unit tests use) or, for floats, we tend to use `(1pd26.16)`.

**Comment by warrickball** [comment]
[Fixed](https://testhub.mesastar.org/binary_time_delta_coeff/commits/dd45c1a) in dd45c1a. I don't know why that buggy build action is triggering either...

**Comment by warrickball** [comment]
Are we waiting on anything here? @orlox has approved and it looks like I fixed any ifort-related errors, so it looks like it should be okay to me. The unexpected CI action doesn't look like an issue with the changes in the PR.

**Comment by evbauer** [comment]
Seems to be passing here and on [testhub](https://testhub.mesastar.org/binary_time_delta_coeff/commits/9de0c6d). Should we go ahead with a rebase and merge?

**Pull request merged**
