### PR TITLE
ForUM as replacement for hdf5io module

### PR DESCRIPTION
**Pull request by rhdtownsend**
Currently, the hdf5io module in MESA (which provides a simple interface to the HDF5 i/o library) is built using source files copied across from [forum](https://github.com/rhdtownsend/forum) (Fortran Utility Modules). While a little janky, this has worked fine in the past.

However, in trying to update to a new release of GYRE (which also uses forum), I discovered that subtle differences in MESA and GYRE's respective forum code was causing link errors.

The most sensible fix, IMHO, is to replace MESA's hdf5io module with forum itself, and then have both MESA and GYRE link to the same library. This set of changes accomplishes the task as follows:

* Add new 'forum' subdir, which builds lib/libforum.a(or .so) and include/forum_m.mod
* Replace hdf5io with forum in LIBS_MESA_NUMERICS def in utils/makefile_header
* Change code in rates, kap and star to 'use forum_m' rather than 'use hdf5io_lib'
* Delete 'hdf5io' subdir

### CODE REVIEW

**Comment by rhdtownsend** [comment]
For the record, this fails on older SDKs because forum does an explicit check for SDK 23.7.2.

**Comment by warrickball** [comment]
I probably won't have a chance to look more closely before the weekend but what makes SDK 23.7.2 (or .3?) a requirement? It looks like the SDK check also stopped [the ifort build I launched last night](https://testhub.mesastar.org/forum/commits/5e7e967). Forum doesn't seem to have its own docs but I can try to build it with ifort myself (as I already do with `crmath`) if necessary.

**Comment by rhdtownsend** [comment]
TBH, this is the oldest version with gfortran 13, which I’ve been running for almost a year now on all my development machines. I’m not sure there’s any specific language feature that requires this, though — just that older SDKs are untested (and likewise not guaranteed to work with MESA).

> On Jun 5, 2024, at 3:04 AM, Warrick Ball ***@***.***> wrote:
> 
> 
> I probably won't have a chance to look more closely before the weekend but what makes SDK 23.7.2 (or .3?) a requirement? It looks like the SDK check also stopped the ifort build I launched last night. Forum doesn't seem to have its own docs but I can try to build it with ifort myself (as I already do with crmath) if necessary.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by rhdtownsend** [comment]
Got things building OK with SDK 21.4.1 (and more recent).

**Comment by rhdtownsend** [comment]
@warrickball any chance to check it out? I'm itching to move on to integrating the new GYRE release!

**Comment by warrickball** [comment]
I was able to briefly start wading into the ForUM build system over the weekend but only got as far as commenting out the check in `$MESA_DIR/forum/forum/build` and instead running into the fact that I've unset `MESASDK_ROOT` here:
```
$ cd $MESA_DIR/forum
$ ./install
Traceback (most recent call last):
  File "./fypp_deps", line 9, in <module>
    sys.path.insert(0, '{:s}/lib/python'.format(os.environ.get('MESASDK_ROOT')))
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "./fypp_deps", line 9, in <module>
    sys.path.insert(0, '{:s}/lib/python'.format(os.environ.get('MESASDK_ROOT')))
TypeError: unsupported format string passed to NoneType.__format__
make[2]: *** No rule to make target 'test_order.f90', needed by '.depend/test_order.anc'.  Stop.
make[1]: *** [Makefile:13: all] Error 2
make: *** [makefile_base:28: all] Error 2
```
I'll try to wander through and eliminate any other explicit MESASDK env var references this evening. I don't think this is intractable, I just didn't have the time to press on.

**Comment by rhdtownsend** [comment]
This path stuff is so that fypp_deps can find the fypp preprocessor Python module. Here’s some replacement code that should work around the issue:

if 'MESASDK_ROOT' in os.environ:
    sys.path.insert(0, '{:s}/lib/python'.format(os.environ['MESASDK_ROOT']))
import fypp

(you’ill also have to install fypp; this can be done using pip).

cheers,

Rich


> On Jun 11, 2024, at 2:07 AM, Warrick Ball ***@***.***> wrote:
> 
> 
> I was able to briefly start wading into the ForUM build system over the weekend but only got as far as commenting out the check in $MESA_DIR/forum/forum/build and instead running into the fact that I've unset MESASDK_ROOT here:
> $ cd $MESA_DIR/forum
> $ ./install
> Traceback (most recent call last):
> File "./fypp_deps", line 9, in <module>
> sys.path.insert(0, '{:s}/lib/python'.format(os.environ.get('MESASDK_ROOT')))
> TypeError: unsupported format string passed to NoneType.__format__
> Traceback (most recent call last):
> File "./fypp_deps", line 9, in <module>
> sys.path.insert(0, '{:s}/lib/python'.format(os.environ.get('MESASDK_ROOT')))
> TypeError: unsupported format string passed to NoneType.__format__
> make[2]: *** No rule to make target 'test_order.f90', needed by '.depend/test_order.anc'. Stop.
> make[1]: *** [Makefile:13: all] Error 2
> make: *** [makefile_base:28: all] Error 2
> 
> I'll try to wander through and eliminate any other explicit MESASDK env var references this evening. I don't think this is intractable, I just didn't have the time to press on.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by rhdtownsend** [comment]
In fact, a cleaner approach is to remove all the MESASDK_ROOT stuff from fypp_deps, and just add a clause to Make.inc that sets PYTHONPATH appropriately. I’ll push out a new release with this fix.

> On Jun 11, 2024, at 9:42 AM, RICHARD H D TOWNSEND ***@***.***> wrote:
> 
> This path stuff is so that fypp_deps can find the fypp preprocessor Python module. Here’s some replacement code that should work around the issue:
> 
> if 'MESASDK_ROOT' in os.environ:
>    sys.path.insert(0, '{:s}/lib/python'.format(os.environ['MESASDK_ROOT']))
> import fypp
> 
> (you’ill also have to install fypp; this can be done using pip).
> 
> cheers,
> 
> Rich
> 
> 
>> On Jun 11, 2024, at 2:07 AM, Warrick Ball ***@***.***> wrote:
>> 
>> 
>> I was able to briefly start wading into the ForUM build system over the weekend but only got as far as commenting out the check in $MESA_DIR/forum/forum/build and instead running into the fact that I've unset MESASDK_ROOT here:
>> $ cd $MESA_DIR/forum
>> $ ./install
>> Traceback (most recent call last):
>> File "./fypp_deps", line 9, in <module>
>> sys.path.insert(0, '{:s}/lib/python'.format(os.environ.get('MESASDK_ROOT')))
>> TypeError: unsupported format string passed to NoneType.__format__
>> Traceback (most recent call last):
>> File "./fypp_deps", line 9, in <module>
>> sys.path.insert(0, '{:s}/lib/python'.format(os.environ.get('MESASDK_ROOT')))
>> TypeError: unsupported format string passed to NoneType.__format__
>> make[2]: *** No rule to make target 'test_order.f90', needed by '.depend/test_order.anc'. Stop.
>> make[1]: *** [Makefile:13: all] Error 2
>> make: *** [makefile_base:28: all] Error 2
>> 
>> I'll try to wander through and eliminate any other explicit MESASDK env var references this evening. I don't think this is intractable, I just didn't have the time to press on.
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you authored the thread.Message ID: ***@***.***>
> 
> --
> Rich Townsend • Professor of Astronomy
> Astronomy Department • University of Wisconsin-Madison
> Phone: 608-262-1752 • E-mail: ***@***.***


--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by warrickball** [comment]
Thanks! The workaround gets me as far as not finding HDF5
```
$ ./install
MAKEDEP libforum
MAKEDEP test_order
hdf5io_m.f90:55:8:

   55 |    use hdf5
      |        1
Fatal Error: Cannot open module file ‘hdf5.mod’ for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [Make.inc:177: .depend/hdf5io_m.anc] Error 1
make[1]: *** [Makefile:13: all] Error 2
make: *** [makefile_base:28: all] Error 2

/rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/forum/make
FAILED
```
I'm guessing the issue is the line in `$MESA_DIR/forum/forum/build/Makefile`
```
LDFLAGS = `lapack_link` `hdf5_link` `lapack95_link`
```
not resolving to anything useful but I didn't get any further by copying the line I use in my MESA `makefile_header`, which is:
```
LOAD_HDF5 = -L${HDF5_DIR}/lib -lhdf5_fortran -lhdf5 -lz
INCLUDE_HDF5 = -I${HDF5_DIR}/include
```
I tried
```
LDFLAGS = -L${HDF5_DIR}/lib -lhdf5_fortran -lhdf5 -lz -I${HDF5_DIR}/include
```
to no avail.

**Comment by rhdtownsend** [comment]
You should be able to set the path to the HDF5 module directory by setting the FFLAGS variable in Makefile:

FFLAGS = -I${HDF5_DIR}/include

cheers,

Rich

> On Jun 11, 2024, at 4:38 PM, Warrick Ball ***@***.***> wrote:
> 
> 
> Thanks! The workaround gets me as far as not finding HDF5
> $ ./install
> MAKEDEP libforum
> MAKEDEP test_order
> hdf5io_m.f90:55:8:
> 
> 55 | use hdf5
> | 1
> Fatal Error: Cannot open module file ‘hdf5.mod’ for reading at (1): No such file or directory
> compilation terminated.
> make[2]: *** [Make.inc:177: .depend/hdf5io_m.anc] Error 1
> make[1]: *** [Makefile:13: all] Error 2
> make: *** [makefile_base:28: all] Error 2
> 
> /rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/forum/make
> FAILED
> 
> I'm guessing the issue is the line in $MESA_DIR/forum/forum/build/Makefile
> LDFLAGS = `lapack_link` `hdf5_link` `lapack95_link`
> 
> not resolving to anything useful but I didn't get any further by copying the line I use in my MESA makefile_header, which is:
> LOAD_HDF5 = -L${HDF5_DIR}/lib -lhdf5_fortran -lhdf5 -lz
> INCLUDE_HDF5 = -I${HDF5_DIR}/include
> 
> I tried
> LDFLAGS = -L${HDF5_DIR}/lib -lhdf5_fortran -lhdf5 -lz -I${HDF5_DIR}/include
> 
> to no avail.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by warrickball** [comment]
I'm chipping away at this while waiting for other stuff to run, a few minutes at a time. Between your `FFLAGS` suggestion and `FC=ifort `, I seemed to build the `forum` successfully, albeit with a lot of warnings from `ifort` because it doesn't understand `gfortran` options (but I can work on that).

I now get to
```
/rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/kap
building kap package.

COMPILE_CMD ../private/kap_aesopus.f90
../private/kap_aesopus.f90(28): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [CINTER_M]
  use forum_m, only: hdf5io_t, OPEN_FILE_RO
------^
../private/kap_aesopus.f90(80): error #6457: This derived type name has not been declared.   [HDF5IO_T]
    type(hdf5io_t) :: hi, hi_ts
---------^
../private/kap_aesopus.f90(28): error #6580: Name in only-list does not exist or is not accessible.   [HDF5IO_T]
  use forum_m, only: hdf5io_t, OPEN_FILE_RO
---------------------^
../private/kap_aesopus.f90(28): error #6580: Name in only-list does not exist or is not accessible.   [OPEN_FILE_RO]
  use forum_m, only: hdf5io_t, OPEN_FILE_RO
-------------------------------^
../private/kap_aesopus.f90(119): error #6404: This name does not have a type, and must have an explicit type.   [HI]
    hi = hdf5io_t(filename, OPEN_FILE_RO)
----^
../private/kap_aesopus.f90(119): warning #8889: Explicit declaration of the EXTERNAL attribute is required.   [HDF5IO_T]
    hi = hdf5io_t(filename, OPEN_FILE_RO)
---------^
../private/kap_aesopus.f90(119): error #6404: This name does not have a type, and must have an explicit type.   [OPEN_FILE_RO]
    hi = hdf5io_t(filename, OPEN_FILE_RO)
----------------------------^
/tmp/ifortv8TWe6.i90(616): catastrophic error: Too many errors, exiting
compilation aborted for ../private/kap_aesopus.f90 (code 1)
make: *** [makefile_base:124: kap_aesopus.o] Error 1

/rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/kap/make
FAILED


/rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/kap
./build_and_test FAILED
```
My hunch is that this is something about the way `ifort` makes us copy `.mod` files into `$MESA_DIR/include`.

**Comment by rhdtownsend** [comment]
That’s puzzling. Is there a forum_m.mod file in $MESA_DIR/include?

> On Jun 12, 2024, at 3:16 PM, Warrick Ball ***@***.***> wrote:
> 
> 
> I'm chipping away at this while waiting for other stuff to run, a few minutes at a time. Between your FFLAGS suggestion and FC=ifort , I seemed to build the forum successfully, albeit with a lot of warnings from ifort because it doesn't understand gfortran options (but I can work on that).
> I now get to
> /rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/kap
> building kap package.
> 
> COMPILE_CMD ../private/kap_aesopus.f90
> ../private/kap_aesopus.f90(28): error #7002: Error in opening the compiled module file. Check INCLUDE paths. [CINTER_M]
> use forum_m, only: hdf5io_t, OPEN_FILE_RO
> ------^
> ../private/kap_aesopus.f90(80): error #6457: This derived type name has not been declared. [HDF5IO_T]
> type(hdf5io_t) :: hi, hi_ts
> ---------^
> ../private/kap_aesopus.f90(28): error #6580: Name in only-list does not exist or is not accessible. [HDF5IO_T]
> use forum_m, only: hdf5io_t, OPEN_FILE_RO
> ---------------------^
> ../private/kap_aesopus.f90(28): error #6580: Name in only-list does not exist or is not accessible. [OPEN_FILE_RO]
> use forum_m, only: hdf5io_t, OPEN_FILE_RO
> -------------------------------^
> ../private/kap_aesopus.f90(119): error #6404: This name does not have a type, and must have an explicit type. [HI]
> hi = hdf5io_t(filename, OPEN_FILE_RO)
> ----^
> ../private/kap_aesopus.f90(119): warning #8889: Explicit declaration of the EXTERNAL attribute is required. [HDF5IO_T]
> hi = hdf5io_t(filename, OPEN_FILE_RO)
> ---------^
> ../private/kap_aesopus.f90(119): error #6404: This name does not have a type, and must have an explicit type. [OPEN_FILE_RO]
> hi = hdf5io_t(filename, OPEN_FILE_RO)
> ----------------------------^
> /tmp/ifortv8TWe6.i90(616): catastrophic error: Too many errors, exiting
> compilation aborted for ../private/kap_aesopus.f90 (code 1)
> make: *** [makefile_base:124: kap_aesopus.o] Error 1
> 
> /rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/kap/make
> FAILED
> 
> 
> /rds/projects/2017/ballwh-stellar-modelling/mesa/mesahub/kap
> ./build_and_test FAILED
> 
> My hunch is that this is something about the way ifort makes us copy .mod files into $MESA_DIR/include.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by warrickball** [comment]
There is. This is `ifort` shenanigans. Compare the `atm` module, where we have to copy additional `.mod` files when using `ifort`. From `$MESA_DIR/atm/makefile_base`:
https://github.com/MESAHub/mesa/blob/9fc77aacaa7f3a1f08380ce7af1a4f2d5c081e3c/atm/make/makefile_base#L55-L66

I expect I just need to figure out some similar copies here but it won't happen tonight.

**Comment by rhdtownsend** [comment]
I think I’ve figured out a fix for the Intel issue — more shortly...

> On Jun 12, 2024, at 3:46 PM, Warrick Ball ***@***.***> wrote:
> 
> 
> There is. This is ifort shenanigans. Compare the atm module, where we have to copy additional .mod files when using ifort. From $MESA_DIR/atm/makefile_base:
> https://github.com/MESAHub/mesa/blob/9fc77aacaa7f3a1f08380ce7af1a4f2d5c081e3c/atm/make/makefile_base#L55-L66
> I expect I just need to figure out some similar copies here but it won't happen tonight.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by rhdtownsend** [comment]
OK, latest commit ([2efbb01]) includes a pre-release of forum 1.0.2. This offers a make flag, RE_EXPORT_MOD_SYMS, that when set to yes will re-export all use'd module symbols from the forum_m module. This should allow you to build with Intel Fortran *without* having to copy all the other .mod files from forum into $MESA_DIR/include (just forum_m.mod).

Should this work, we can use a similar technique in the atm module.

**Comment by rhdtownsend** [comment]
Pinging @warrickball -- have you had a chance to try out RE_EXPORT_MOD_SYMS yet?

**Comment by warrickball** [comment]
I'm experimenting with it this very moment... I've made a few goofy errors but give me another 20 minutes or so.

**Comment by warrickball** [comment]
Yip, that seems to work, after I set `FC = ifort` and comment out the SDK version check. I'm happy that this is close enough to consistently buildable, even though I haven't actually set any `ifort` options (so it mostly complains about not understanding various `gfortran` flags).

**Comment by warrickball** [comment]
Note that I don't build GYRE under `ifort` because it didn't work at some point (probably years ago by now) and I haven't tried again since.

**Comment by Debraheem** [comment]
@rhdtownsend @warrickball , can you add some brief documentation of this change to the changelog?

**Comment by rhdtownsend** [comment]
Just to clarify, you mean the changelog for the *next* release, after the current release candidate goes out? Because these changes are not part of the rc, right?

> On Jun 17, 2024, at 3:42 PM, Ebraheem Farag ***@***.***> wrote:
> 
> 
> @rhdtownsend @warrickball , can you add some brief documentation of this change to the changelog?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

--
Rich Townsend • Professor of Astronomy
Astronomy Department • University of Wisconsin-Madison
Phone: 608-262-1752 • E-mail: ***@***.***

**Comment by Debraheem** [comment]
Yes, don't worry about the release candidate. Push to the changelog in main. The changes will eventually propagate into the next release (i.e. the full release in August, r24.08.1).

**Pull request merged**
