### PR TITLE
Turn off gold2_tolerances in defaults but leave on in test suite

### PR DESCRIPTION
**Pull request by rjfarmer**
Works on #490 

This should leave test cases that explicitly set gold2 on/off alone and only sets cases which don't specify gold2 to now be on.

https://testhub.mesastar.org/rf%2Fgold2_off/commits/dc8a8c4

### CODE REVIEW

**Comment by evbauer** [comment]
Should I go ahead and push my suggested changes to the default values of `warn_when_large_rel_run_E_err` and `max_abs_rel_run_E_err` to be part of this PR as well?

**Comment by rjfarmer** [comment]
Sure go ahead and push

**Comment by evbauer** [comment]
Ok, pushed! I think I've got cannon back online running these tests too. It seems to be having some filesystem issues (lots of failures on the git lfs checks earlier today), but I was finally able to get past that.

**Comment by fxt44** [comment]
looks good to my eyes. go for the merge.

**Review by evbauer — APPROVED** [review]

**Pull request merged**
