### PR TITLE
TDC Solver Improvements

### PR DESCRIPTION
**Pull request by adamjermyn**
This PR implements an improved TDC solver which always picks the slowest-decaying solution when there are multiple solutions present. This both improves the stability of the solution (avoiding jumping between solutions when parameters are perturbed) and gives smoother transitions from convective to radiative.

There are currently two failing tests:
- ccsn_IIp
- zams_to_cc_80

@orlox Want to look at ccsn_IIp? I'm looking at zams_to_cc_80.

### CODE REVIEW

**Comment by warrickball** [comment]
Is it just me or does this not appear to be compiling as of 4954a5c ([TestHub](https://testhub.mesastar.org/tdc_search/commits/4954a5c))?

**Comment by fxt44** [comment]
just compiled 5f1abd on an m1 without issue.  i have't seen a compile failure recently.

**Comment by fxt44** [comment]
oops, i did HEAD, not this tdc  branch.

**Comment by orlox** [comment]
Can give a look to ccsn_IIp on Thursday

**Comment by adamjermyn** [comment]
I'm getting a compilation error on `const` of all things!

```
/Users/ajermyn/Dropbox/Software/MESA/mesa-dev-git/const
building const package.

MAKEDEPF90
COMPILE_CMD ../public/const_def.f90
COMPILE_CMD ../public/const_lib.f90
LIB_TOOL libconst.a
MAKEDEPF90
TEST_COMPILE ../src/test_const.f
LOADER ../tester

0a1,23
>                                       pi     3.1415926535897931E+00
>                                     ln10     2.3025850929940455E+00
>                              boltz_sigma     5.6703744191844259E-05
>                            boltz_sigma*4     2.2681497676737704E-04
>                     boltz_sigma*4/clight     7.5657332502799993E-15
>                       boltz_sigma/clight     1.8914333125699998E-15
>                                     crad     7.5657332502799993E-15
>                                   secyer     3.1557600000000000E+07
>                                     Msun     1.9884098706980504E+33
>                                     Rsun     6.9570000000000000E+10
>                                     Lsun     3.8280000000000003E+33
>                                       ly     9.4607304725808000E+17
>                                  m_earth     5.9721678677913790E+27
>                                       au     1.4959787070000000E+13
>                                      amu     1.6605390671738466E-24
>                                       mn     1.6749274980400001E-24
>                                       mp     1.6726219236900000E-24
>                                       me     9.1093837015000000E-28
>                                 planck_h     6.6260701499999999E-27
>                                       qe     4.8032047125702634E-10
>                                      avo     6.0221407599999999E+23
>                                   clight     2.9979245800000000E+10
>                                     kerg     1.3806490000000000E-16

/Users/ajermyn/Dropbox/Software/MESA/mesa-dev-git/const/test
TEST FAILED -- compare test_output to tmp.txt


/Users/ajermyn/Dropbox/Software/MESA/mesa-dev-git/const
./build_and_test FAILED
```

**Comment by fxt44** [comment]
is tmp.txt all zeros?

**Comment by warrickball** [comment]
`bluebear_ifort` fails because of the test output in `turb`, which is consistent with `cannon_conroy_intel`. If the new output looks OK, I can commit that.
```
$ diff -uw ../.mesa_test/work/turb/test/{test_output,tmp.txt}
--- ../.mesa_test/work/turb/test/test_output    2022-01-18 21:29:03.352664000 +0000
+++ ../.mesa_test/work/turb/test/tmp.txt        2022-01-18 21:37:34.008900863 +0000
@@ -36,3 +36,12 @@
                     dt, gradT, conv_vel_start, conv_vel    7.2840558626389941D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
                     dt, gradT, conv_vel_start, conv_vel    7.4297369798917748D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
                     dt, gradT, conv_vel_start, conv_vel    7.5783317194896108D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    7.7298983538794027D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    7.8844963209569903D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    8.0421862473761303D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    8.2030299723236533D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    8.3670905717701260D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    8.5344323832055295D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    8.7051210308696398D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    8.8792234514870324D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
+                    dt, gradT, conv_vel_start, conv_vel    9.0568079205167737D+02   -1.2020505435123704D+05    5.2320588000000000D+07    0.0000000000000000D+00
```

**Comment by warrickball** [comment]
I'm fairly confident the error was the test output being short when committed in 4954a5c. It's produced by a loop from `j=0,30`, so there should be 31 lines, as there are in the failing `tmp.txt` files, but there are only 22 in `test_output`.

**Comment by fxt44** [comment]
ahh. makes sense.

**Comment by adamjermyn** [comment]
@fxt44 The issue was on my end. Old SDK.

@warrickball Yeah that's right. I think I've fixed it now.

**Comment by adamjermyn** [comment]
We're down to two failing tests: `12M_pre_ms_to_core_collapse` and `ccsn_IIp`. The former I think is just a timestep control issue, so I'm hoping that won't be too hard to fix...

**Comment by adamjermyn** [comment]
Okay `12M_pre_ms_to_core_collapse` is passing now. Any progress on `ccsn_IIp` @orlox ?

**Comment by orlox** [comment]
@adamjermyn past week has been more chaotic than expected and haven't found time for MESA. Will work on it tomorrow morning.

**Comment by orlox** [comment]
I think this is just related to the nastiness  of the energy deposition phase in ccsn_IIP. We have a constant and very large eps_nuc being applied to a fixed fraction of the star producting some unreasonable convective boundaries, probably doing it with a smooth eps_nuc that turns on and off nicely, and smooths to zero further out from the core could make things better behaved. Will see if I manage to set that up later today and test it

**Comment by orlox** [comment]
Or on a second look, the `max_abs_du_div_cs_for_convection` option is at play here affecting convection. Investigating...

**Comment by adamjermyn** [comment]
Just as a heads up, the `tdc_gamma` branch is coming along nicely. That branch implements a suggestion Lars had for making TDC & MLT Cox agree in the steady state limit. Along the way I've also fixed a few edge cases in the TDC solver. Unclear if they're relevant for `ccsn_IIp`.

If we get the `tdc_gamma` branch to green on Testhub before this branch then I'd suggest we just merge that one, as that includes all the improvements in this one plus more.

Currently there are just five failing cases on `tdc_gamma`. Two of those are asteroseismology ones that just need recalibration. The other three are `ccsn_IIp`, `cburn_inward`, and `12M_pre_ms_to_core_collapse`. I'm working on `12M_pre_ms_to_core_collapse` and `cburn_inward` now. @orlox It might be better to focus your `ccsn_IIp` efforts on that branch (to the extent that they involve tweaking parameters)...

**Comment by orlox** [comment]
I'll jump then to `tdc_gamma`, thanks for the heads up

**Comment by warrickball** [comment]
> Two of those are asteroseismology ones that just need recalibration.

I should be able to work on this later today.

**Comment by adamjermyn** [comment]
Ok both `12M_pre_ms_to_core_collapse` and `cburn_inward` now pass on `tdc_gamma`, so I'm going to close this PR and open a new one for that branch.

**Pull request closed without merging**
