### PR TITLE
Inlist arrays

### PR DESCRIPTION
**Pull request by matthiasfabry**
addresses #368 as envisioned.

This cleans up several hundred lines into neat loops and makes this feature more easily extendable to a larger amount of extra inlists.

### CODE REVIEW

**Comment by warrickball** [comment]
Nice! As I already said in the issue, I think this is an improvement and, at a glance, it looks like you've caught all the occurrences (including in the docs!). I think three things remain to be done.

1. The `astero` module should be refactored in the same way. This should be straightforward.
2. Can you merge into a target branch `MESAHub:inlist_arrays`? We learned from the last PR that we should do things that way so we can run the full test suite before merging with `MESAHub:main`. We might need to create the `MESAHub:inlist_arrays` branch for you to merge into.
3. This will be disruptive for users, so it'd be nice to distribute a script that will make the appropriate changes. I haven't cooked one up but I imagine there's a single `sed` command that will do it, though we need something that works on both Macs and Linux.

Also, though I don't mind too much, I would've gone a step further and removed the `read_extra_star_job_inlist` logical completely in favour of just ignoring empty filenames but perhaps there's a use case I'm not foreseeing.

**Comment by evbauer** [comment]
I've updated the base branch to `MESAHub:inlist_arrays`. I'll go ahead and merge onto that branch so we can get some testing started, but will also leave the PR open so we can get Warrick's suggestions addressed and you can potentially push more commits as necessary on your end. Nice work Matthias!

**Comment by evbauer** [comment]
You can see testing results here: https://testhub.mesastar.org/inlist_arrays/commits

**Comment by evbauer** [comment]
Oops, merging into `MESAHub:inlist_arrays` closed the PR, obviously. I've opened #471 (and referenced this PR) for when we're ready to merge all the way into main.

I guess this multi-stage PR merging procedure is still something we need to get used to. Is there a more elegant way than what I've just done?

**Comment by warrickball** [comment]
Am I right that you did some sort of command-line merge that unexpectedly closed the PR? I wouldn't have expected the PR to close either but we're learning. In that case, we might have to let the contributor get it to a point where the devs take over then do the merge so that testing can begin. Still not ideal: we somehow want users to be able to respond to TestHub failures.

**Comment by evbauer** [comment]
I actually didn't do anything from the command line. Everything was through the github online interface.

Overall, this seems to have gone pretty well. It's just a bit more convoluted than I had previously appreciated, but Matthias opened a new PR with fixes onto the right testing branch, so everything looks fine to me.

**Pull request merged**
