### PR TITLE
Add neutrino capture rates

### PR DESCRIPTION
**Pull request by rjfarmer**
Start on adding neutrino capture rates.

Its slow as molasses going uphill but its a starting point.

Also no idea yet if its actual spitting out sensible numbers

### CODE REVIEW

**Comment by fxt44** [comment]
cool. what's the target application(s) ?

**Comment by rjfarmer** [comment]
Core collapse nucleosynthesis, at least initially. Idea being that the user specifies some neutrino flux(space,time) distribution (so we ignore the full complexity of neutrino transport) and then we see what happens.

**Comment by fxt44** [comment]
fluorine is fun! where are the artes coming from?

**Comment by rjfarmer** [comment]
I'm following what skynet does (their appendix C)

**Comment by fxt44** [comment]
ahh, hence the added integration routine.

**Comment by rjfarmer** [comment]
Yup, though that I think will need replacing already with something better. It needs to take alot of sub steps to even begin to converge on a value

**Comment by fxt44** [comment]
well, there are fermi functions in there, so not unlike in an eos. a tuned quadrature scheme may do well. alternatively tabulate off-line rather than on the fly.

**Comment by rjfarmer** [comment]
You know after plotting the rates, they are smooth enough that we can just pre-compute some polynomial fits in python and load the coefficients into mesa. 

Much simpler and also alot easier to get the derivatives out.

**Comment by fxt44** [comment]
way easier! probably accurate 'enough".

**Pull request closed without merging**
