### PR TITLE
Add tests to input/output of eosdt.

### PR DESCRIPTION
**Pull request by adamjermyn**
This PR introduces new tests to the input quantities for the EOS in eosdt and the returned outputs. These tests are:
1. No EOS return quantity may be NaN.
2. No negative pressures.
3. No negative sound speeds.
4. No negative adiabatic indices.
5. No negative specific heats.
6. No negative chi's.
7. No negative or NaN compositions.
8. No negative or NaN X or Z or abar or zbar.
9. No (logRho,logT) outside the plane (logT_lo,logT_hi,logRho_lo,logRho_hi), which I've set to match the range covered by HELM (though these could get out of sync if HELM changes down the road).
10. No negative Rho or T.

Once merged this resolves issue #285.

I'm currently waiting to merge pending results from [Testhub](https://testhub.mesastar.org/eos_better_tests/commits/12dec6c).

### CODE REVIEW

**Comment by adamjermyn** [comment]
Exciting! Lots of cases fail. As you might expect these all look like they're cases where the EOS was either failing silently or somehow ignoring bad inputs. I'll start tracking them down.

**Comment by fxt44** [comment]
GIGO to the rescue (or demise)!

**Comment by adamjermyn** [comment]
Some of the failures are because the root finders for e.g. eosPT go out of bounds. Presumably beforehand they'd go out of bounds and then somehow hop back in? Here's an example, from rsp_BEP:
```
 eval1_mesa_Rho_given_PT failed           0
 P   239.82657328270977     
 T   17385.095374334280     
 rho_guess   2.1459613882639316E-010
 eval1_mesa_Rho_given_PT failed           0
 P   239.82657328270977     
 T   17384.921524246398     
 rho_guess   2.1459828479855314E-010
                                                    T_1           0    5.8593662214878832D+03
                                                   Tmax           0    1.7385095374334313D+04
                                            resid_T_min           0   -1.0000000000000280D+00
                                            resid_T_max           0    5.1944688649472917-315
 eval1_mesa_Rho_given_PT failed         149
 P   239.82657328270977     
 T   17384.921524246398     
 rho_guess   2.1459828479855314E-010
 failed in do_rsp_build
 failed in build_rsp_model
 star_create_RSP_model ierr          -1
 do_load1_star ierr          -1
 do_before_evolve_loop ierr          -1
 do_before_evolve_loop ierr          -1
```

Any thoughts on how to handle that?

**Comment by fxt44** [comment]
sharing two experiences here, neither direct, but perhaps relevant. one, is during solution for the nuclear statistical equilibrium where mass and charge conservation are the constraint equations. here, the 2d root finder commonly explores solutions that are wildly away from sum X = 1, yet because the resulting differences are large, the root finder abandons that search direction. two, is during solutions under a constant pressure constraint. here, the root finder may well venture off the thermodynamic manifold where there is no solution for the (P,rho) pair. again, the root finder bails on that direction as the errors are large. bottom line is that in both cases i let the root findsersdo their thing without trying to constrain intermediate results. mileage may vary in mesa.

**Comment by evbauer** [comment]
Any idea why this branch is getting checksum mismatches?
https://testhub.mesastar.org/eos_better_tests/commits/9c83e09

**Comment by adamjermyn** [comment]
No idea. In principle all that's changed is that it raises ierr /= 0 in
`eosDT_get` when you query with invalid inputs (and likewise when EOS
returns invalid outputs). Maybe there's an FPE that we only avoided by dint
of allowing GIGO?

-Adam

**Comment by adamjermyn** [comment]
Now that the TDC merge is in I merged `main` into this branch. We're still getting checksum mismatches and lots of failures. Looks like just lots of cases of `ierr` not being caught correctly by the routines that call the EOS.

I don't have the time/energy/interest to push forward on this, so I'm going to close out this PR. I'll leave the issue open as an enhancement in case someone else wants to take it on.

**Pull request closed without merging**
