### PR TITLE
Ideal eos

### PR DESCRIPTION
**Pull request by adamjermyn**
Introduces a new EOS made of ideal ion + radiation for use as a backplane.

@evbauer and @orlox maybe take this for a spin and let me know how it works? I'll also be looking at testhub before merging of course...

### CODE REVIEW

**Comment by orlox** [comment]
Also for this composition there is a funny logP coming from HELM in the dragons region, but I guess that's unrelated to the implementation of the ideal EOS. Here near the edge of HELM lnP drops to very negative values.

eos_plotter
eos_regions

**Comment by fxt44** [comment]
the funny P is coming from helm's coulomb corrections. it would be better, i think,  if skye covered the dragons region.

**Comment by adamjermyn** [comment]
Yeah 🙁 . The only reason we use HELM there in fact is that Skye goes bad...

**Comment by fxt44** [comment]
didn't the latest cms eos cover this dragon range? i recall aaron looked into it.

**Comment by evbauer** [comment]
I was just in the process of writing a message about this. I think the failure in `make_o_ne` is fairly benign...

**Comment by evbauer** [comment]
Oh, yes, those certainly should be zero for an ideal EOS. Was it just giving uninitialized garbage for those?

**Comment by adamjermyn** [comment]
I would guess that you're hitting a kap boundary that low in temperature...

-Adam

**Comment by adamjermyn** [comment]
I'll get the extra fraction info in `star` on Monday if no one beats me to it. Then I guess it's just down to what testhub says and what we need to clean up...

**Pull request merged**
