### PR TITLE
GYRE update

### PR DESCRIPTION
**Pull request by rhdtownsend**
This PR updates both GYRE and ForUM to the current HEAD of their respective main branches. This is to allow full testing within the MESA build system; eventually, we can switch over to the most-recent releases.

### CODE REVIEW

**Comment by rhdtownsend** [comment]
Just saw the PR number. This is clearly a beastly update!

**Comment by rhdtownsend** [comment]
OK, some build failures -- will try to figure out why things are going awry...

**Comment by Debraheem** [comment]
I enjoyed having the gyre in MESA in the massive star test_suites, as I use it to test for stable YSG and RSG pulsations, although I'm fine to remove it.

**Comment by Debraheem** [comment]
Please do not merge this pr until you add documentation to the changelog and wherever else it might be necessary. There is still no docs for the forum switch either, or the python3 dependancy.

**Comment by rhdtownsend** [comment]
> Please do not merge this pr until you add documentation to the changelog and wherever else it might be necessary. There is still no docs for the forum switch either, or the python3 dependancy.

I've updated changelog.rst on main to document the switch from hdf5io to forum, and the new requirement for Python (>= 3.5) to build MESA. We might want to flag that requirement separately at the top of the changelog (e.g., in a rst note or warning) to make sure that it doesn't get overlooked.

Working on the changelog for gyre now...

**Comment by Debraheem** [comment]
>We might want to flag that requirement separately at the top of the changelog (e.g., in a rst note or warning) to make sure that it doesn't get overlooked.

I reused your text to add a small warning to the top of the changelog and the 'installing mesa' page.

**Review by Debraheem — APPROVED** [review]

**Pull request merged**
